apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-services
spec:
  generators:
  - git:
      repoURL: https://github.com/b8kings0ga/tgitops.git
      revision: HEAD
      files:
      - path: "envs/dev/us-east-1/*/values.yaml"
  template:
    metadata:
      name: '{{path.basename}}-dev-service'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/b8kings0ga/tgitops.git
        targetRevision: HEAD
        path: charts/golden-charts
        helm:
          valuesFiles:
          - "{{path}}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true