apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-vclusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/b8kings0ga/tgitops.git
      revision: HEAD
      files:
      - path: "vclusters/dev/sg/*/vcluster.yaml"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        chart: vcluster
        repoURL: https://charts.loft.sh
        helm:
          releaseName: '{{path.basename}}'
          valueFiles:
          - "{{path}}/vcluster.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true