apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "golden-charts.fullname" . }}
  labels:
    {{- include "golden-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "golden-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "golden-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http